#
# Module manifest for module 'NimbleHighlight'
#
# Generated by: NimbleThing
#
# Generated on: 21/07/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'NimbleHighlight.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'dfbdb4fe-2833-4ebf-bd3b-3f5164332887'

# Author of this module
Author = 'NimbleThing'

# Company or vendor of this module
CompanyName = 'NimbleThing Pty. Ltd.'

# Copyright statement for this module
Copyright = '(c) NimbleThing 2023. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell module to Syntax Highlight Powershell Code from Powershell with Powershell'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''
# RequiredModules = @()
# RequiredAssemblies = @()
# ScriptsToProcess = @()
# TypesToProcess = @()
# FormatsToProcess = @()
# NestedModules = @()

FunctionsToExport = @('Show-Code')

CmdletsToExport = @()
VariablesToExport = @()
AliasesToExport = @()

# DscResourcesToExport = @()

# ModuleList = @()
# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('PowerShell', 'SyntaxHighlighting', 'Console', 'ANSI')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/secretGeek/highlight/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/secretGeek/highlight'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Initial release'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

